nodeLinker: node-modules
enableGlobalCache: true

yarnPath: .yarn/releases/yarn-4.6.0.cjs

packageExtensions:
  'ts-jest@*':
    peerDependencies:
      '@types/jest': '*'

compressionLevel: mixed

enableTelemetry: false

logFilters:
  - code: YN0002 # MISSING_PEER_DEPENDENCY
    level: discard
  - code: YN0060 # INCOMPATIBLE_PEER_DEPENDENCY
    level: discard
